# Generated by Django 4.2.5 on 2023-09-24 20:25

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='締切'),
        ),
    ]
